//
//  DSJailbreakEnv.m — 「越狱模式」实现：jbroot 解析 + entitlements 诊断 + 如实探针
//
//  本文件**不执行任何漏洞、不碰内核**，只做三件事：
//    1) 按 roothide / rootless 的实际做法解析 jbroot（逐条尝试、每条记结果）；
//    2) 打印本 App 自己的 entitlements（判断「权限没给」还是「沙盒在拦」）；
//    3) 用逐路径 + 真实 errno 的探针如实给出结论（EPERM=沙盒拒绝 / EACCES=权限不足 /
//       ENOENT=不存在 / EROFS=只读），绝不假装成功。
//
//  只用公开 POSIX 接口与签名确定的 Security 接口；不猜任何私有函数签名。
//

#import "DSJailbreakEnv.h"
#import "DSSignatureInfo.h"
#import "DSFSAccessProbe.h"

#import <dlfcn.h>
#import <errno.h>
#import <limits.h>
#import <stdlib.h>
#import <string.h>
#import <unistd.h>
#import <sys/stat.h>
#import <dirent.h>

#pragma mark - 小工具

static BOOL ds_jb_exists(const char *path)
{
    if (path == NULL) return NO;
    struct stat st;
    return (stat(path, &st) == 0);
}

static BOOL ds_jb_is_dir(const char *path)
{
    if (path == NULL) return NO;
    struct stat st;
    if (stat(path, &st) != 0) return NO;
    return S_ISDIR(st.st_mode);
}

static BOOL ds_jb_is_symlink(const char *path)
{
    if (path == NULL) return NO;
    struct stat st;
    return (lstat(path, &st) == 0 && S_ISLNK(st.st_mode));
}

/// 读符号链接目标（相对链接按所在目录解析）；失败返回 nil
static NSString *ds_jb_readlink(NSString *path)
{
    if (path.length == 0) return nil;
    char buf[PATH_MAX];
    memset(buf, 0, sizeof(buf));
    ssize_t n = readlink(path.fileSystemRepresentation, buf, sizeof(buf) - 1);
    if (n <= 0) return nil;
    NSString *target = [NSString stringWithUTF8String:buf];
    if (target.length == 0) return nil;
    if (![target hasPrefix:@"/"]) {
        target = [[path stringByDeletingLastPathComponent] stringByAppendingPathComponent:target];
    }
    return [target stringByStandardizingPath];
}

static NSString *ds_jb_env(NSString *name)
{
    const char *v = getenv(name.UTF8String);
    if (v == NULL) return nil;
    NSString *s = [NSString stringWithUTF8String:v];
    return s.length ? s : nil;
}

/// 列目录（POSIX，避免 NSFileManager 抛异常）；失败返回 nil 并回填 errno
static NSArray<NSString *> *ds_jb_list(NSString *path, int *outErrno)
{
    if (path.length == 0) return nil;
    DIR *d = opendir(path.fileSystemRepresentation);
    if (d == NULL) {
        if (outErrno) *outErrno = errno;
        return nil;
    }
    NSMutableArray<NSString *> *names = [NSMutableArray array];
    struct dirent *e = NULL;
    while ((e = readdir(d)) != NULL) {
        NSString *n = [NSString stringWithUTF8String:e->d_name];
        if (n.length) [names addObject:n];
    }
    closedir(d);
    if (outErrno) *outErrno = 0;
    return names;
}

#pragma mark - jbroot 解析

/// roothide 的标记名：官方文档写的是 `.jbroot`（"each directory containing a mach-o file
/// will automatically generate a .jbroot symbolic link that pointing to the jailbreak root
/// directory, usually generated by dpkg when installing packages"），实际实现里也见过
/// `.jbroot-<随机后缀>`，所以两种都认。
static BOOL ds_jb_is_marker(NSString *name)
{
    if (name.length == 0) return NO;
    return [name isEqualToString:@".jbroot"] || [name hasPrefix:@".jbroot-"];
}

/// 在一个目录里找 `.jbroot` / `.jbroot-*` 标记，返回解析后的越狱根（含符号链接解析与校验）
static NSString *ds_jb_find_marker_in(NSString *dir, NSMutableArray<NSString *> *notes)
{
    int err = 0;
    NSArray<NSString *> *names = ds_jb_list(dir, &err);
    if (names == nil) {
        [notes addObject:[NSString stringWithFormat:@"  · 列 %@ → 失败 errno=%d %@", dir, err, DSFilesystemErrnoName(err)]];
        return nil;
    }
    NSString *hit = nil;
    for (NSString *n in names) {
        if (ds_jb_is_marker(n)) { hit = n; break; }
    }
    if (hit == nil) {
        [notes addObject:[NSString stringWithFormat:@"  · 列 %@ → 成功但没有 .jbroot 标记（%lu 项）",
                          dir, (unsigned long)names.count]];
        return nil;
    }

    NSString *marker = [dir stringByAppendingPathComponent:hit];
    NSString *resolved = marker;
    if (ds_jb_is_symlink(marker.fileSystemRepresentation)) {
        NSString *target = ds_jb_readlink(marker);
        if (target.length) {
            resolved = target;
            [notes addObject:[NSString stringWithFormat:@"  · 找到标记 %@ → 符号链接指向 %@ ✓", marker, resolved]];
        } else {
            [notes addObject:[NSString stringWithFormat:@"  · 找到标记 %@（是符号链接但 readlink 失败）", marker]];
        }
    } else {
        [notes addObject:[NSString stringWithFormat:@"  · 找到标记 %@（不是符号链接，直接当越狱根）", marker]];
    }

    BOOL hasUsr = ds_jb_is_dir([resolved stringByAppendingPathComponent:@"usr"].fileSystemRepresentation);
    BOOL hasBin = ds_jb_is_dir([resolved stringByAppendingPathComponent:@"bin"].fileSystemRepresentation);
    [notes addObject:[NSString stringWithFormat:@"  · 校验 %@：usr=%@ bin=%@", resolved,
                      hasUsr ? @"有" : @"无", hasBin ? @"有" : @"无"]];
    return resolved;
}

NSString *DSJailbreakRootResolutionReport(void)
{
    NSMutableArray<NSString *> *notes = [NSMutableArray array];
    NSString *root = nil;

    // ① 环境变量
    for (NSString *name in @[@"JBROOT", @"ROOTHIDE"]) {
        NSString *v = ds_jb_env(name);
        if (v.length == 0) {
            [notes addObject:[NSString stringWithFormat:@"① 环境变量 %@：未设置", name]];
            continue;
        }
        if (ds_jb_is_dir(v.fileSystemRepresentation)) {
            [notes addObject:[NSString stringWithFormat:@"① 环境变量 %@=%@ → 目录存在 ✓", name, v]];
            if (root == nil) root = v;
        } else {
            [notes addObject:[NSString stringWithFormat:@"① 环境变量 %@=%@ → 但目录不存在（errno=%d %@）",
                              name, v, errno, DSFilesystemErrnoName(errno)]];
        }
    }

    // ② 本 App 自己容器 / 包体内的 `.jbroot-*` 标记（roothide 让沙盒内 App 找到越狱根的方式）
    if (root == nil) {
        NSMutableArray<NSString *> *dirs = [NSMutableArray array];
        NSString *home = NSHomeDirectory();
        if (home.length) {
            [dirs addObject:home];
            [dirs addObject:[home stringByDeletingLastPathComponent]];
        }
        NSString *bundle = NSBundle.mainBundle.bundlePath;
        if (bundle.length) {
            [dirs addObject:bundle];
            [dirs addObject:[bundle stringByDeletingLastPathComponent]];
        }
        [notes addObject:[NSString stringWithFormat:@"② 本 App 容器/包体内的 .jbroot 标记（候选 %lu 个目录）—— "
                          @"roothide 官方文档：dpkg 会在每个含 Mach-O 的目录里生成 .jbroot 符号链接指向越狱根",
                          (unsigned long)dirs.count]];
        for (NSString *dir in dirs) {
            NSString *found = ds_jb_find_marker_in(dir, notes);
            if (found.length) { root = found; break; }
        }
    }

    // ③ roothide 标志目录 + 可见的 .jbroot-*
    if (root == nil) {
        if (ds_jb_exists("/var/mobile/Library/roothide")) {
            [notes addObject:@"③ /var/mobile/Library/roothide 存在 ✓（roothide 环境标志）"];
        } else {
            [notes addObject:[NSString stringWithFormat:@"③ /var/mobile/Library/roothide 不可见（errno=%d %@）",
                              errno, DSFilesystemErrnoName(errno)]];
        }
        for (NSString *dir in @[@"/var/containers/Bundle/Application", @"/", @"/var/mobile"]) {
            NSString *found = ds_jb_find_marker_in(dir, notes);
            if (found.length) { root = found; break; }
        }
    }

    // ④ rootless：/var/jb
    if (root == nil) {
        if (ds_jb_is_dir("/var/jb")) {
            [notes addObject:@"④ /var/jb 存在 ✓（rootless：Dopamine / palera1n rootless）"];
            root = @"/var/jb";
        } else {
            [notes addObject:[NSString stringWithFormat:@"④ /var/jb 不可见（errno=%d %@）",
                              errno, DSFilesystemErrnoName(errno)]];
        }
    }

    [notes addObject:root.length
        ? [NSString stringWithFormat:@"结论：jbroot = %@", root]
        : @"结论：没有解析出 jbroot（沙盒内看不到越狱目录属正常，不代表没越狱）"];

    return [notes componentsJoinedByString:@"\n"];
}

NSString * _Nullable DSJailbreakRootPath(void)
{
    static NSString *cached = nil;
    static BOOL done = NO;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        // 直接复用报告里的解析逻辑：把结论行挑出来，保证"报告"与"返回值"永远一致
        NSString *report = DSJailbreakRootResolutionReport();
        for (NSString *line in [report componentsSeparatedByString:@"\n"]) {
            if ([line hasPrefix:@"结论：jbroot = "]) {
                cached = [line substringFromIndex:[@"结论：jbroot = " length]];
                break;
            }
        }
        done = YES;
    });
    (void)done;
    return cached;
}

#pragma mark - entitlements 诊断

NSString *DSJailbreakEntitlementReport(void)
{
    NSMutableString *out = [NSMutableString string];
    [out appendString:@"本 App 自己的 entitlements（只读诊断；判断「权限没给」还是「沙盒在拦」）:\n"];
    [out appendString:DSSignatureEntitlementDiagnosticReport()];

    BOOL platform = [DSSignatureEntitlementValue(@"platform-application") isEqualToString:@"true"]
                 || [DSSignatureEntitlementValue(@"platform-application") isEqualToString:@"1"];
    NSString *containerRequired = DSSignatureEntitlementValue(@"com.apple.private.security.container-required");
    BOOL containerOff = [containerRequired isEqualToString:@"false"] || [containerRequired isEqualToString:@"0"];

    if (platform && containerOff) {
        [out appendString:@"  结论：platform-application ✓ 且 container-required=false ✓ —— "
                         "本 App 应可不受沙盒限制；若探针仍 EPERM，说明是越狱环境在拦（见下面的逐路径 errno）。\n"];
    } else if (DSSignatureIsTrollStoreInstalled()) {
        [out appendString:@"  结论：TrollStore 安装，但**没有** platform-application / container-required=false —— "
                         "这正是 roothide 下 TrollStore App 读不到系统路径的原因；"
                         "请改用越狱版（.deb，装进 <jbroot>/Applications/）安装。\n"];
    } else {
        [out appendString:@"  结论：没有越狱 App 需要的沙盒例外 entitlements。\n"];
    }
    return out;
}

#pragma mark - 环境判定

BOOL DSJailbreakLooksJailbroken(void)
{
    // 1) 签名（不需要任何权限，最可靠）
    if (DSSignatureIsTrollStoreInstalled()) return YES;

    // 2) 环境变量
    for (NSString *name in @[@"JBROOT", @"ROOTHIDE", @"DYLD_INSERT_LIBRARIES", @"THEOS_PACKAGE_INSTALL_PREFIX"]) {
        NSString *v = ds_jb_env(name);
        if (v.length == 0) continue;
        NSString *lower = v.lowercaseString;
        if ([lower containsString:@"roothide"] || [lower containsString:@"jbroot"]
            || [lower containsString:@"substrate"] || [lower containsString:@"substitute"]
            || [name isEqualToString:@"JBROOT"] || [name isEqualToString:@"ROOTHIDE"]) {
            return YES;
        }
    }

    // 3) 越狱痕迹路径
    if (ds_jb_exists("/var/mobile/Library/roothide")) return YES;
    if (ds_jb_is_dir("/var/jb")) return YES;
    if (ds_jb_exists("/Library/MobileSubstrate/MobileSubstrate.dylib")) return YES;

    // 4) 越狱库能加载（只 dlopen、不调用）
    for (NSString *lib in @[@"/var/jb/usr/lib/libroothide.dylib", @"/usr/lib/libroothide.dylib"]) {
        if (!ds_jb_exists(lib.fileSystemRepresentation)) continue;
        void *h = dlopen(lib.UTF8String, RTLD_LAZY);
        if (h != NULL) { dlclose(h); return YES; }
    }

    // 5) 本 App 容器里有没有 roothide 标记
    return DSJailbreakRootPath().length > 0;
}

NSString *DSJailbreakEnvironmentSummaryLine(void)
{
    NSString *root = DSJailbreakRootPath();
    BOOL readable = DSFilesystemProbeReadable();
    BOOL writable = DSFilesystemProbeWritable();
    return [NSString stringWithFormat:@"越狱模式：jbroot=%@ · 可读=%@ · 可写=%@ · %@",
            root.length ? root : @"(未解析到)",
            readable ? @"是" : @"否",
            writable ? @"是" : @"否",
            DSFilesystemAccessSummaryLine()];
}

#pragma mark - 激活（不跑任何漏洞）

static NSString *gJBLastStage = @"未开始";

NSString *DSJailbreakLastStage(void) { return gJBLastStage; }

int DSJailbreakActivate(NSString *_Nullable *_Nullable detail)
{
    NSMutableArray<NSString *> *reasons = [NSMutableArray array];

    gJBLastStage = @"环境判定";
    BOOL looksJB = DSJailbreakLooksJailbroken();

    gJBLastStage = @"jbroot 解析";
    NSString *root = DSJailbreakRootPath();

    gJBLastStage = @"文件访问探针";
    BOOL readable = DSFilesystemProbeReadable();
    BOOL writable = DSFilesystemProbeWritable();

    NSString *summary = [NSString stringWithFormat:
        @"越狱模式（不执行任何漏洞）：越狱特征=%@ · jbroot=%@ · 可读=%@ · 可写=%@ · uid=%d",
        looksJB ? @"有" : @"无",
        root.length ? root : @"(未解析到)",
        readable ? @"是" : @"否",
        writable ? @"是" : @"否",
        getuid()];

    if (writable) {
        gJBLastStage = @"完成（可读写）";
        if (detail) *detail = [NSString stringWithFormat:
            @"%@ —— 直接用 POSIX 读写沙盒外路径，不需要内核漏洞。", summary];
        return 0;
    }

    if (readable) {
        gJBLastStage = @"完成（只读可达）";
        if (detail) *detail = [NSString stringWithFormat:
            @"%@ —— 沙盒外只读可达（能浏览、能导出；写入仍受限制）。", summary];
        return 0;
    }

    // 读也读不到：如实说明卡在哪
    gJBLastStage = @"失败（沙盒拒绝）";
    [reasons addObject:summary];
    [reasons addObject:DSFilesystemAccessSummaryLine()];

    if (DSSignatureIsTrollStoreInstalled()) {
        [reasons addObject:
            @"检测到 TrollStore 安装，但本 App 仍读不到系统路径 —— roothide 下 TrollStore 安装的 App "
            @"**不会**获得越狱权限（roothide 的设计就是让 App 看不到越狱）。"
            @"要做的事（二选一）："
            @"① 用 Sileo / Zebra 安装 myfilza_0.9.2_iphoneos-arm64e.deb（桌面名 myfilza JB）；"
            @"② deb 装不上时（例如 dpkg 报 “./rootfs/... Read-only file system”），"
            @"   改用**手动安装包** myfilza-jb-manual.zip：解压后把 myfilza.app / entitlements.plist / "
            @"install.sh 放同一目录，在越狱终端执行 sh install.sh（详见包内 README.txt）。"
            @"越狱版 bundle id 是 com.dsfile.app.jb，与侧载版的 com.dsfile.app 是两个 App，可共存；"
            @"装到 <jbroot>/Applications/ 并带上越狱 entitlements 后，越狱模式即可读写全盘。"
            @"（不想折腾的话，把「访问路径」改成「仅内核」/「自动」走内核那条。）"];
    } else if (looksJB) {
        [reasons addObject:
            @"检测到越狱特征，但本 App 仍受沙盒限制 —— 本 App 没有被授予沙盒例外。"
            @"要做的事：用 Sileo / Zebra 安装 myfilza_0.9.2_iphoneos-arm64e.deb，"
            @"或用手动安装包 myfilza-jb-manual.zip（解压后在越狱终端执行 sh install.sh）；"
            @"两者都会把 App 装进 <jbroot>/Applications/ 并注入越狱 entitlements"
            @"（platform-application / no-sandbox / storage.AppBundles / storage.AppDataContainers）；"
            @"或把「访问路径」改成「仅内核」/「自动」走内核那条。"];
    } else {
        [reasons addObject:
            @"没有检测到越狱特征（签名里没有 TROLLTROLL、没有 JBROOT/ROOTHIDE、"
            @"/var/jb 与 .jbroot-* 也不可见）—— 这台设备要么没越狱，要么越狱对 App 完全隐藏。"
            @"请把「访问路径」改成「自动」或「仅内核」。"];
    }

    if (detail) *detail = [reasons componentsJoinedByString:@" "];
    return looksJB ? 1030 : 1031;
}
